FROM python:3.9-slim

WORKDIR /app

# Copy only the requirements file first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the necessary backend files
COPY src/ ./src/
COPY Procfile .
COPY runtime.txt .

# Expose the port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "src.api.serve:app", "--host", "0.0.0.0", "--port", "8000"] 