[build]
  base = "src"
  publish = "public"
  command = """
    echo 'Installing dependencies...' &&
    npm install &&
    echo 'Building JavaScript...' &&
    npm run build &&
    echo 'Copying static files...' &&
    mkdir -p public &&
    cp static/index.html public/ &&
    cp static/test.html public/ &&
    if [ -d "static/css" ]; then cp -r static/css public/; fi &&
    if [ -d "static/images" ]; then cp -r static/images public/; fi &&
    if [ -d "static/components" ]; then cp -r static/components public/; fi &&
    echo 'Checking build output:' &&
    ls -la public/ &&
    ls -la public/js/ &&
    cat public/js/agents.js | head -n 5 &&
    echo 'Build complete!'
  """

# Redirects and headers are CRITICAL for SPAs to work correctly
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/*"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"
    
[[headers]]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css" 