[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://kind-gwenora-papajams-0ddff9e5.koyeb.app/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/*"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"
    
[[headers]]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css" 