[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

# Redirects and headers are CRITICAL for SPAs to work correctly
[[redirects]]
  from = "/api/*"
  to = "https://kind-gwenora-papajams-0ddff9e5.koyeb.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/js/*"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"
    
[[headers]]
  for = "/css/*"
    [headers.values]
    Content-Type = "text/css" 